#!/usr/bin/env python3
"""
get-font.py — Self-host ANY Google Font in one command (GDPR-safe).

    python scripts/get-font.py "Josefin Sans"

What it does:
  1. Downloads the needed woff2 files into  /fonts/
  2. (Re)writes  /fonts.css  with the matching @font-face rules
  3. Prints the value to paste into settings.csv  →  font_family

That's the whole font swap. index.html already links fonts.css, so once the
script finishes and you set font_family, the new font is live.

By default it grabs the weights this site uses (normal 300/400/500/600 +
italic 300/400). If a font doesn't have one of those weights Google simply
omits it — harmless. Edit WEIGHTS below to change the set.

Requires only Python 3 (no third-party packages).
"""
import os
import re
import sys
import urllib.request

BASE = os.path.join(os.path.dirname(__file__), '..')
FONTS_DIR = os.path.join(BASE, 'fonts')
CSS_OUT = os.path.join(BASE, 'fonts.css')

# (style, weight): style 0 = normal, 1 = italic
WEIGHTS = [(0, 300), (0, 400), (0, 500), (0, 600), (1, 300), (1, 400)]

HEADERS = {
    'User-Agent': ('Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
                   'AppleWebKit/537.36 (KHTML, like Gecko) '
                   'Chrome/124.0.0.0 Safari/537.36')
}


def fetch(url):
    req = urllib.request.Request(url, headers=HEADERS)
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read()


def main():
    if len(sys.argv) < 2:
        print('Usage: python scripts/get-font.py "Font Name"')
        sys.exit(1)

    family = ' '.join(sys.argv[1:]).strip()
    slug = re.sub(r'[^A-Za-z0-9]', '', family)  # "Josefin Sans" -> "JosefinSans"
    os.makedirs(FONTS_DIR, exist_ok=True)

    ital = ';'.join(f'{s},{w}' for s, w in sorted(WEIGHTS))
    url = ('https://fonts.googleapis.com/css2?family='
           + family.replace(' ', '+') + ':ital,wght@' + ital + '&display=swap')

    print(f'Fetching "{family}" from Google Fonts...')
    try:
        css = fetch(url).decode('utf-8')
    except Exception as e:
        print(f'ERROR: could not fetch the font CSS: {e}')
        print('Check the font name matches Google Fonts exactly.')
        sys.exit(1)

    # Parse every @font-face block
    faces = []
    for block in re.findall(r'@font-face\s*\{([^}]+)\}', css, re.S):
        def g(pat):
            m = re.search(pat, block)
            return m.group(1).strip() if m else ''
        urlm = re.search(r"url\(([^)]+)\)\s*format\('woff2'\)", block)
        if not urlm:
            continue
        faces.append({
            'style': g(r'font-style:\s*([^;]+)') or 'normal',
            'weight': g(r'font-weight:\s*([^;]+)') or '400',
            'range': g(r'unicode-range:\s*([^;]+)'),
            'url': urlm.group(1).strip(),
        })

    if not faces:
        print('ERROR: no @font-face rules found — is the font name exact?')
        sys.exit(1)

    # One file per (weight, style): prefer the "latin" subset (covers Western
    # European incl. German umlauts ä ö ü ß), otherwise the first available.
    chosen = {}
    for f in faces:
        key = (f['weight'], f['style'])
        if 'U+0000' in f['range']:
            chosen[key] = f
        elif key not in chosen:
            chosen[key] = f

    rules = []
    for (weight, style), f in sorted(chosen.items(), key=lambda kv: (kv[0][1], kv[0][0])):
        suffix = f'{weight}{"i" if style == "italic" else ""}'
        fname = f'{slug}-{suffix}.woff2'
        print(f'  downloading {fname}')
        try:
            with open(os.path.join(FONTS_DIR, fname), 'wb') as out:
                out.write(fetch(f['url']))
        except Exception as e:
            print(f'    ERROR downloading {fname}: {e}')
            continue
        rules.append(
            f'@font-face{{font-family:"{family}";font-style:{style};'
            f'font-weight:{weight};font-display:swap;'
            f'src:url("fonts/{fname}") format("woff2")}}')

    # Preserve any hand-added @font-face blocks (e.g. a display font) that live
    # below this marker, so swapping the MAIN font here never wipes them.
    sentinel = ('/* ===== ADDITIONAL SELF-HOSTED FONTS '
                '(added by hand; preserved across get-font.py runs) ===== */')
    preserved = ''
    if os.path.exists(CSS_OUT):
        old = open(CSS_OUT, encoding='utf-8').read()
        i = old.find(sentinel)
        if i != -1:
            preserved = '\n' + old[i:].rstrip() + '\n'

    header = ('/* AUTO-GENERATED by scripts/get-font.py — do not edit above the marker.\n'
              f'   Main font: {family} (self-hosted from /fonts/, GDPR-safe).\n'
              '   Re-run the script with a different name to swap the MAIN font.\n'
              '   Hand-added faces below the "ADDITIONAL SELF-HOSTED FONTS" marker\n'
              '   (e.g. the display font) are kept across runs. */\n')
    with open(CSS_OUT, 'w', encoding='utf-8') as out:
        out.write(header + '\n'.join(rules) + '\n' + preserved)

    print(f'\nDone — wrote fonts.css ({len(rules)} faces) and the woff2 files.')
    print('Final step: in settings.csv set  font_family  to:')
    print(f'  "{family}", sans-serif')


if __name__ == '__main__':
    main()
